### ISSUE TITLE
Keep all the explicit ports even if offering nice `uri` & `port` credentials

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cf-containers-broker#6]
Currently, you can either blindly pass all `8080/tcp` port bindings back in `credentials` OR you can select one of them to become the traditional styled `hostname`/`port`/`uri` credentials:

``` yaml
        "credentials": {
          "hostname": "10.3.2.6",
          "port": "49153",
          "uri": "rethinkdb://10.3.2.6:49153"
        },
```

In the latter case, I'd still like all the other port bindings to be passed through. This would allow me to find the HTTP web UI port for rethinkdb; whilst the binding could still be primarily a binding for the TCP port (as advertised above).

That is, I'd like the `credentials` above to be:

``` yaml
        "credentials": {
          "hostname": "10.3.2.6",
          "port": "49153",
          "uri": "rethinkdb://10.3.2.6:49153",
          "8080/tcp": ...
        },
```
